### PR TITLE
Update fasta2fasta.py

### PR DESCRIPTION
**Pull request by IanSudbery**
Replaced %i with %%i in help for "--template-identifier" which was causing error when running '--help'

### CODE REVIEW

**Comment by IanSudbery** [comment]
hmmm.... The only change I made was to add a % in a help string. This can't be changing the output from a function test. Has a dependency version change changed the order of an output?

**Comment by Acribbs** [comment]
At least the ubuntu build fail with the same error now and I can debug more easily, but the missing image issue in Mac is problematic, I only know how to fix these locally.

**Comment by Acribbs** [comment]
Thinking out aloud: I think the issues with the Mac build may be related to paramiko, which we have removed in new cgatcore. I just released a new conda version of cgatcore and have re-initiated the tests to see if they improve, they won't fix the ubuntu tests, but should help improve the OSX build (fingers crossed) and I can work from there.

**Comment by Acribbs** [comment]
Hmm, didn't work, by the conda tests didn't pick up correct cgatcore

**Comment by Acribbs** [comment]
So the issue with the Mac build has been fixed but I am struggling to work out what is wrong with the testing for bam2bam. It looks like the original tests are broken. Some I have re-ran locally and I cannot see any differences (e.g. strip sequence) from reference. Others (unset methods), the output looks as expected when running locally, but the reference does not match the input data, also the set_mapq.bam isn't indexed so until I indexed this sample, I couldn't run this test. Its like the tests were run using the wrong input, but I am struggling to work out why this would have been the case ...

I think that given the tests look to be a mess and I am not entirely sure what has gone wrong, I wonder if I should remake all of the test from scratch for bam2bam and check to make sure the outputs are as expected, it may take some time to do this though. 

What you think @IanSudbery ?

**Pull request merged**
