### PR TITLE
Deal with empty MEME files in MEME.py

### PR DESCRIPTION
**Pull request by IanSudbery**
Contains checks to deal with empty MEME files, and py3 changes to deal with generators being created rather than lists.

### CODE REVIEW

**Comment by IanSudbery** [comment]
Don't undertand why checks are failing?

**Comment by Acribbs** [comment]
Ah I think this may be due to the way travis has changed its directory system. I have seen this error before I just can’t remember where or when. Will have a think tonight and see if I can remember.

**Comment by Acribbs** [comment]
I fixed the master branch with new Miniconda install. It fixed the master branch. I then merged that into this branch. It seems like this branch was 138 commits behind the master. Not sure why its so behind? Anyway, I get the pull request passing but not the push. Will do the same with the other branch and see how it goes

**Comment by Acribbs** [comment]
Since the pr is passing I would have thought that it would be safe to merge

**Comment by IanSudbery** [comment]
The branches are behind master because we only update our master when we start a new project, but we need the bug fixes straight away.

Sorry I should have created a branch just for the PR and merged it with origin/master myself first.

**Pull request merged**
