### PR TITLE
travis tests are failing and it seems on local testing on mac that ch…

### PR DESCRIPTION
**Pull request by Acribbs**
…anging pysam to 0.15.2 makes bam2bam work

### CODE REVIEW

**Comment by Acribbs** [comment]
@sebastian-luna-valero Travis tests are failing now and im not sure why. In our previous travis test in october ran to completion. Forcing Travis to re-run tests on the master seems to make it fail. On local testing on my mac, when I downregulate pysam from 0.15.3 to 0.15.2 bam2bam script works, while it originally failed for the following reason:
```
from cgat.BamTools.bamtools import bam2bam_filter_bam, SetNH
  File "libcalignedsegment.pxd", line 66, in init cgat.BamTools.bamtools
ValueError: pysam.libcalignedsegment.PileupColumn has the wrong size, try recompiling. Expected 88, got 72
```

Not sure if this is the reason for the tests failing on travis (I installed cgat-apps using conda, while our install script picks up the git branch) but I have pinned the version of pysam to see if it makes a difference. 

Do you have any suggestions?

**Comment by Acribbs** [comment]
ok, well that failed to do anything

**Comment by sebastian-luna-valero** [comment]
Well, you're right; updating `pysam` from `0.15.2` to `0.15.3` makes the following tests fail:

* bam2bam.py:
```
cat /home/travis/build/cgat-developers/cgat-apps/tests/bam2bam.py/nh_flag.bam | cgat bam2bam  -v 0 --log=/dev/null --method=filter --filter-method=unique --method=filter --filter-method=mapped --output-sam

cat /home/travis/build/cgat-developers/cgat-apps/tests/bam2bam.py/sample_gsnap.bam | cgat bam2bam  -v 0 --log=/dev/null --method=filter --filter-method=NM --reference-bam-file=/home/travis/build/cgat-developers/cgat-apps/tests/bam2bam.py/sample_star.bam
```

* bam2stats.py:
```
cat /home/travis/build/cgat-developers/cgat-apps/tests/bam2stats.py/paired.bam | cgat bam2stats  --force-output

cat /home/travis/build/cgat-developers/cgat-apps/tests/bam2stats.py/paired.bam | cgat bam2stats  --output-details --fastq-file=/home/travis/build/cgat-developers/cgat-apps/tests/bam2stats.py/paired.fastq.1.gz --force-output
```
Do you know why?

Best regards,
Sebastian

**Comment by Acribbs** [comment]
I think there may have been something wrong with the build on 0.15.3. See this https://github.com/pysam-developers/pysam/pull/814

**Comment by Acribbs** [comment]
@sebastian-luna-valero I think we leave pysam pinned to 0.15.2 for the time being, until pysam has sorted it automatic pypi issues. Will merge, please revert if you dont agree. Thanks for your help.

**Pull request merged**
